process.env.PORT = process.env.PORT || 3002;
process.env.NODE_ENV = 'production';
process.env.CADUCIDAD_TOKEN = 60 * 60 * 24 * 30;
process.env.SEED = process.env.SEED || 'desarrollo';
process.env.PGUSER = "rvelasco";
process.env.PGHOST = "10.10.10.44";
process.env.PGPASSWORD = "bGE9629gQQ33";
process.env.PGDATABASE = "db_ace";
process.env.PGPORT = 5422;
